### ISSUE TITLE
Remove string-check for pattern

### ISSUE THREAD

**Issue by headjump** [superwolff/metalsmith-in-place#107]
You use "multimatch", this adds array-patterns to minimatch. So you should allow them as pattern ;)

**Comment by ismay** [comment]
Ah yeah, thanks for the heads up. Now allowing array patterns as well.

**Comment by ismay** [comment]
Will release this as 3.0.0, since support for iojs and 0.12 has also been dropped.

**Comment by ismay** [comment]
Released as 3.0.0
