### ISSUE TITLE
Plugin corrupts images?

### ISSUE THREAD

**Issue by gaggle** [superwolff/metalsmith-in-place#110]
When I use metalsmith-in-place images come out corrupted, i.e. the browser displays them as broken and I can't open them in image viewers. If I disable this plugin the images are copied across correctly.

I've tested this as `"metalsmith-in-place": "^2.0.1"` and `"metalsmith-in-place": "^3.0.0"`

I note this plugin has an old Changelog entry:

> 0.5.2 - July 9, 2014
> --
> 82 | --------------------
> 83 | * fix breaking binary files

Which seems to relate to [this commit](https://github.com/superwolff/metalsmith-in-place/commit/a1bd29c18d7dd5cba6849a24efdf538baec556f7#diff-6d186b954a58d5bb740f73d84fe39073R45), which has code ala

`if (!utf8(data.contents)) return false;`

I can't find the corresponding code in the latest code, presumably the code above is prior to a rework at some point.

If you feel this sounds like a reasonable line of logic I'm happy to catch this via test and/or suggest a PR, but wanted to put out this feeler first to validate my base understanding.

(and thanks for providing the plugin!)

# EDIT
I put up a PR suggestion here: https://github.com/superwolff/metalsmith-engine-jstransformer/pull/8

That repo doesn't appear to have tests so it is hard to prove the effectiveness of my proposed change, but making this change in-line in my project appears to work.

**Comment by ismay** [comment]
Ah yeah, thanks for that 👍 Forgot to take care of that in the move.

> I can't find the corresponding code in the latest code, presumably the code above is prior to a rework at some point.

Yeah that's right. It was before the move to jstransformers.

> That repo doesn't appear to have tests so it is hard to prove the effectiveness of my proposed change, but making this change in-line in my project appears to work.

Yup, it still needs a decent testing suite.

I took a look at your pr, and I think the best solution here is not to return if the file is binary. I think it'd be better to only stringify the contents of the file if it's actually going to be transformed.

Right now we're always stringifying, regardless of whether it's going to be transformed (see [line 30](https://github.com/superwolff/metalsmith-engine-jstransformer/blob/master/lib/render-file.js#L30)). But it might be better to do that around [line 44](https://github.com/superwolff/metalsmith-engine-jstransformer/blob/master/lib/render-file.js#L44). (and then also transforming back to a buffer in the loop, instead of after). A little bit less efficient, but more correct. And it will still allow jstransformers to operate on binary files if they want to.

**Comment by gaggle** [comment]
Hi ismay,

To see if I understand what you're saying I've updated the PR with the render logic moved into the loop. If I should happen across a solution you find acceptable it can always be cleaned up, for now it's just a tool for clear communication.

I resonate with your idea that jstransformers should operate on binary files if it wants, but is it not the case that binary buffer data is inherently corrupted  by casting them to and from strings?

I think to let the transformer work on binary files either the raw buffer must be passed to `#render`:

    file.contents = transform.render(file.contents, options, locals).body;

(well, maybe `file.contents` needs to be passed as a copy, not reference)

Or the buffer should be cast to string with an encoding that preserves binary data:

    const contents = file.contents.toString('base64')
    const transformed = transform.render(contents, options, locals).body;
    file.contents = Buffer.from(transformed, 'base64')

(untested, but going for the general idea)

If you know what you want feel free to close this ticket and the associated PR, I just wanted to highlight the corruption. Or if you're better off guiding me through this I'm happy to hone the PR until it looks right.

**Comment by ismay** [comment]
> I resonate with your idea that jstransformers should operate on binary files if they want, but is it not the case that binary buffer data is inherently corrupted by just casting them to and from strings?

Ah yeah of course, you're right. And I've tried to find jstransformers that operate on binary files, but I couldn't find any. So I think it should be ok to just go with your original approach.

If we then decide to allow binary files we'll have to revisit the logic anyways. Sorry, didn't mean to cause any extra work. If you can reimplement your original solution we should be fine.

**Comment by gaggle** [comment]
Np, happy to help. I've [updated the PR](https://github.com/superwolff/metalsmith-engine-jstransformer/pull/8/) and also added a test to prove the change. It's all very basic but maybe a kernel for that future testing suite :) Happy to make further changes as necessary.

**Comment by ismay** [comment]
Closed in https://github.com/superwolff/metalsmith-engine-jstransformer/pull/8/

**Comment by ismay** [comment]
> Np, happy to help. I've updated the PR and also added a test to prove the change. It's all very basic but maybe a kernel for that future testing suite :) Happy to make further changes as necessary.

Awesome, thank you!

**Comment by ismay** [comment]
Ok, I took the opportunity to update metalsmith-engine-jstransformer a bit. It now has a test suite and some other bells and whistles. Your issue should be fixed for metalsmith-in-place 3.0.1. Thanks again for the help and let me know if you find anything!
