### ISSUE TITLE
Confusing Version

### ISSUE THREAD

**Issue by julmot** [superwolff/metalsmith-in-place#115]
What is going on with this project? Confusing versions everywhere.

On GitHub we have two 2.x versions which are no releases. When using v2.0.1 I'm getting an error:

![2017-09-15 21_24_27-cmd](https://user-images.githubusercontent.com/8310677/30499850-63a0923e-9a5c-11e7-9a69-7039be547fef.png)

And on npm, another version, v3.0.1 exists, but not on GitHub... Please clear this confusion in the documentation.

![2017-09-15 21_23_21-metalsmith-in-place](https://user-images.githubusercontent.com/8310677/30499852-63b9b82c-9a5c-11e7-90ef-568fc3a7b8bf.png)
![2017-09-15 21_23_28-releases superwolff_metalsmith-in-place](https://user-images.githubusercontent.com/8310677/30499851-63af0bc0-9a5c-11e7-8c4b-2b3569412e98.png)
![2017-09-15 21_24_05-releases superwolff_metalsmith-in-place](https://user-images.githubusercontent.com/8310677/30499854-63c82560-9a5c-11e7-9374-84e652584aed.png)

**Comment by ismay** [comment]
Nothing weird is going on with this project. Check the changelog where all versions and changes are documented. Furthermore all tests are passing.

Let me know if nonetheless you've found something that's not covered by the tests. About the github releases, I personally don't use them and don't see the point in maintaining them. Npm is the tool of choice for this project.
