### ISSUE TITLE
Expose consolidate.requires

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#13]
To allow for template engine instances to be configured and passed to consolidate.

See: https://github.com/superwolff/metalsmith-layouts/issues/6

**Comment by jmatsushita** [comment]
Would be great to expose consolidate.requires as I'm trying to adapt this metalsmith plugin https://github.com/losttype/metalsmith-register-helpers to register nunjucks filters and I can't seem to do this with global nunjucks instance.

**Comment by bobylito** [comment]
Thanks for this project. Very helpful :D
Do you plan to release this feature?

**Comment by doodzik** [comment]
I think it depends on how the discussion [here](https://github.com/superwolff/metalsmith-layouts/issues/100) turns out

but if you need it you can install it from master

**Comment by doodzik** [comment]
@bobylito [we are making progress](https://github.com/superwolff/metalsmith-layouts/pull/105)
