### ISSUE TITLE
Extra <p></p> blocks around in-place markup

### ISSUE THREAD

**Issue by jmjf** [superwolff/metalsmith-in-place#20]
This may be user error. 

I'm trying to set up a multi-column Bootstrap layout in Metalsmith with Handlebars. I have a page design that has
```
left-col        right-col
   bottom-wide-section
```
where left-col, right-col, and bottom-wide-section are all user-provided content (markdown).

- Bootstrap requires me to wrap parts of my `{{{content}}}` block in row and column divs.
- Handlebars returns content as a monolithic block and doesn't have provisions for splitting it (as best I can tell).
- Metalsmith can't combine multiple .md files into a multi-part content block (as best I can tell), and even if it could, I doubt Handlebars could address it properly.

So, to get around these limitations, I was trying to use in-place to define rows and columns as follows (reduced test case, only defines row).

**test.md**
```
---
layout: standardPage.hbs
title: "TestPage"
---
{{{inplace.beginRow}}}

This is some test content.

Will there be a blank paragraph block above?

{{{inplace.endRow}}}
```
When my pipeline is markdown -> in-place -> layouts, I get the following output.
```
<div class="body-text" role="main">
    <p>
        <div class="row">
    </p>
    <p>This is some test content.</p>
    <p>Will there be a blank paragraph block above?</p>
    <p>
        </div>
    </p>

</div>
```
Note the `<p>` blocks enclosing the `<div>` and `</div>`. The browser automatically "fixes" the HTML.
**Browser "Fixed" HTML**
```
<div role="main" class="body-text">
    <p>
        </p><div class="row">
    <p></p>

    <p>This is some test content.</p>
    <p>Will there be a blank paragraph block above?</p>
    <p>
        </p></div>
    <p></p>

</div>
```
This creates layout problems by injecting extra paragraph margins and padding in the layout.

Any pipeline that runs markdown first will have the extra `<p>` blocks because markdown wraps the in-place values in `<p>` blocks as shown by the markdown -> layouts (no in-place) pipeline below.
```
<div class="body-text" role="main">
    <p>{{{inplace.beginRow}}}</p>
    <p>This is some test content.</p>
    <p>Will there be a blank paragraph block above?</p>
    <p>{{{inplace.endRow}}}</p>

</div>
```
Running markdown after in-place prevents markdown from rendering content wrapped in divs and other block elements.

Is this expected behavior?

If so, how would one go about assembling a page that requires content to be broken into several pieces on the page? Or how would one inject HTML markup into the content block? (Coding it directly will cause markdown to skip wrapped content, and I'd rather not ask users to write HTML--that's the whole point of markdown.)

Or should in-place (optionally?) remove and immediately adjacent `<p></p>` wrapper?

**Comment by ismay** [comment]
Well, `metalsmith-layouts` will pass `file.contents` to the selected layout as a single `{{contents}}` variable, so there's no way to have multiple content blocks. And `metalsmith-in-place` will process variables in your source files, but that's not the same as applying a layout (if you're using handlebars).

If you want to use handlebars then I'd suggest you use `handlebars-layouts` which allows you to have multiple content areas: https://github.com/shannonmoeller/handlebars-layouts.

Or, you could use a different templating language, like Jade, Jinja, Swig, or Twig, which already have support for these kinds of content blocks.

**Comment by jmjf** [comment]
So, it sounds like this isn't necessarily by explicit design, but isn't surprising either.

Thanks for the tip on handlebars-layouts. After a quick look, my sense is I'll run into the same issues. Either Markdown will wrap the handlebars-layouts helpers in `<p>` blocks or, after handlebars-layouts runs, I'll have trouble getting Markdown to process--or it will undo handlebars-layouts content blocks. I'll come back to this later.

I may investigate one of the other template engines in the long run, but I think I'm going to run into the same issue again unless I have users write content in HTML.

I think the issue is actually with how Markdown is defined. Markdown has no way to define named content blocks. (Even if it did, Handlebars probably couldn't address them). With the content it has, it either wraps everything in `<p>` blocks or ignores content in HTML blocks (like `<div>`). What I really need is a way to tell Markdown, "Ignore these {{ }} or {{{ }}} things." There's also no way I'm aware of in Markdown or Metalsmith to say, "Bind some .md files into a single object with keys left, right, and bottom."

The latter may be a solution that has broader applications (though I'm not sure what yet). Front-matter defines the target file name and key for a given .md. A post-processor plugin runs immediately after markdown and rewrites the files array based on the metadata. But that's more than I have time to do right now.

So, I think I'll try the simple approach first--a plugin that will strip the `<p>` tags from Handlebars-like expressions. This approach also avoids the disk file management issue of having index_a.md, index_b.md, etc.  I was expecting I'd need to go that route, so I've built a regex to identify `<p>`-wrapped Handlebars (except comments). I'll work on getting it plugin-ized and see how it works.

**Comment by jmjf** [comment]
Well, it's easier than I thought. [metalsmith-grep](https://github.com/mrajo/metalsmith-grep) does what I need. I may try to put together a pull request for it to add a file filter argument, but that's all.

For Handlebars, run metalsmith-grep after markdown and before in-place with the regexp below. Wrap Handlebars in a 4-stache (`{{{{ }}}}`), and the regexp will turn it into a 3-stache when wrapped by a `<p>` block with nothing else. That means each 4-stache needs to be in it's own paragraph.

**metalsmith-grep call**
```
	.use(markdown())
	.use(grep({
		subs: [
			{
				search: /<p>\s*\{((\s*\{\{\{\s*(~?([#/][^\s!"#;<=>@`%-,[-^{-~]*)?)\s*@?[^\s!"#;<=>@`%-,[-^{-~]*~?\s*}}}\s*)+)}\s*<\/p>/gi,
				replace: '$1'
			}
		]
	}))
	.use(inplace(...
```
**test.md**
```
---
layout: standardPage.hbs
title: "TestPage"
---
{{{{inplace.beginRow}}}}

This is some test content.

Will there be a blank paragraph block above?

{{{{inplace.endRow}}}}
```
**Output HTML**
```
<div role="main" class="body-text">
    <div class="row">
    <p>This is some test content.</p>
    <p>Will there be a blank paragraph block above?</p>
    </div>
</div>
```

I chose to use a 4-stache to ensure the regexp could never accidentally replace deliberate 3-stache markup, but given the requirement for a surrounding `<p>` block with no other content but whitespace, this is belt-and-suspenders level safety.

**Comment by ismay** [comment]
Ok cool. I'll be closing this then, but let me know if there's anything else!
