### ISSUE TITLE
metadata in partials

### ISSUE THREAD

**Issue by karneaud** [superwolff/metalsmith-in-place#29]
Does the plugin handle metadata in partials?
e.g.

In my template file
template/index.html
```
---
template: main.html
---
```
I have a partial file
template/partials/main.html
```
---
title: Test Title
---
{{> section}}
<p>Test partial</p>
```
and in another partial 
template/partials/section.html
```
<header><h1>{{header}}</header>
<p>{{{content}}</p>
```
I was expecting the result to be
build/index.html

```
<header><h1>Test Title</h1></header>
<p>Test partial</p>
```

however I do not get that expected result. The meta data is just printed out unformatted. Does in-place handle markdowns in partials?

my .json for metalsmith

```
"metalsmith-layouts": {
      "engine": "handlebars",
      "default": "index.html",
      "directory": "template",
      "partials":"template/partials",
      "pattern":"*.html"
    },
    "metalsmith-in-place":
    {
      "engine":"handlebars",
      "partials":"template/partials",
      "pattern": "*.html"
    },
```

**Comment by ismay** [comment]
I think you're confusing a couple of things. You're using the `template` key in your frontmatter, when it should be `layout`. I don't have time to comment on anything else, but try that first. Also, check out the readme, there are examples there which specify exactly how this plugin should work.

I'll get back to you shortly, when I have more time, but try that first.

**Comment by ismay** [comment]
I think you're confusing a couple of things. You're using the `template` key in your frontmatter, but you're using metalsmith-in-place and not metalsmith-templates. I don't have time to comment on anything else, but try using metalsmith-layouts with a `layout` key in your frontmatter. Also, check out the readme, there are examples there which specify exactly how the plugin should work.

I'll get back to you shortly, when I have more time, but try that first.

**Comment by karneaud** [comment]
I'm using metalsmith-layouts along with your metalsmith-in-place.... neither `template` no `layout` works. I have partials and sub partials that use this sort of markdown. I guess the markdown only works on top level items...?

**Comment by karneaud** [comment]
Isn't **metalsmith-templates** deprecated by the way?

**Comment by ismay** [comment]
> Isn't metalsmith-templates deprecated by the way?

Exactly.

>  I guess the markdown only works on top level items...?

I think you mean frontmatter. Metalsmith parses frontmatter for all files in `source`, which is `./src` by default.

**Comment by karneaud** [comment]
Well...I don't get it...I'm new to metalsmith and I'm using the command line to create a one pager. so i have one source file and a template file with several partial files that I INCLUDE into the template file. Some partial files include other partial files that have content with reuse able code and I want to be able to have the partials that do the including to have metadata that can be converted into objects and used in the included partials....


Hope I made sense but i get the feeling I'm using metalsmith wrong....?

**Comment by ismay** [comment]
Ok, can you create a reduced test case that demonstrates the problem (and push it to a github repo)? That'll make it easier for me to take a look at it.

**Comment by karneaud** [comment]
Cool...I'm looking at another solution though....will let you know
