### ISSUE TITLE
Use with handlebars-layouts

### ISSUE THREAD

**Issue by zslabs** [superwolff/metalsmith-in-place#35]
Hi,
I'm attempting to use this plugin to extend blocks provided by [handlebars-layouts](https://www.npmjs.com/package/handlebars-layouts), but it doesn't appear to be working correctly; as all I ever get is `[object Object]` (other Handlebars logic does work however). Here is my Metalsmith setup:

```
Metalsmith(__dirname)
.source('src')
.use(ms_collections({
  pages: {
    pattern: 'pages/**/*.md'
  },
  articles: {
    pattern: 'articles/*.md',
    sortBy: 'date',
    reverse: true
  }
}))
.use(ms_filemetadata([
  {
    pattern: 'articles/*.md',
    metadata: {
      'layout': 'post.html'
    }
  }
]))
.use(ms_helpers({
  directory: '_helpers',
  pattern: /\.js$/
}))
.use(ms_inPlace({
  'engine': 'handlebars',
  'partials': '_partials',
  'pattern': 'pages/**/*.md'
}))
.use(ms_markdown())
.use(ms_moveUp('pages/**/*'))
.use(ms_permalinks({
  linksets: [{
    match: { collection: 'articles' },
    pattern: 'articles/:title',
  }]
}))
.use(ms_layouts({
  engine: 'handlebars',
  default: 'default.html',
  directory: '_layouts',
  partials: '_partials',
  helpers: handlebarsHelpers
}))
// .use(function(files, metalsmith, done) {
//   console.log('Files: ');
//   console.log(files);
//   console.log();
//   console.log('Metalsmith: ');
//   console.log(metalsmith);
// })
//.use(ms_html_minifier())
.destination('build')
.build(function(err) {
  if (err) throw err;
});```

I'm looking to use the helpers provided by that library to extend blocks setup by my Handlebars templates. If you have any other suggestions I'd really appreciate it. Thanks!

**Comment by ismay** [comment]
Difficult for me to judge as your example doesn't cover your entire project (I'm not seeing any `require` and can't see your source files). A general comment I can make is that helpers need to be registered with your handlebars instance. If you want more detailed feedback I'll need a [reduced test case](https://css-tricks.com/reduced-test-cases/) to see what's going on.

I'll close this as it's a support question and doesn't seem to be an issue with metalsmith-in-place itself. But feel free to ask further questions!

**Comment by zslabs** [comment]
HI @ismay,
I think the problem I'm running into is wanting to reference blocks that would be included within metalsmith-layouts (like extending a block created in header.html within a single post), but since in-place would normally be run before metalsmith-layouts, I don't see how this could be possible. Any tips on how to make that work?

**Comment by ismay** [comment]
> but since in-place would normally be run before metalsmith-layouts

Not necessarily. The order can be whatever suits you. But if you can create an example repo I can help you, because right now I've only got part of the information I need.

**Comment by zslabs** [comment]
Hi @ismay,
I created https://github.com/zslabs/metalsmith-test to show you what I have so far. If you look in https://github.com/zslabs/metalsmith-test/blob/master/templates/partials/layout/header.html#L8 you'll see a `header_misc` block that I'd like to be able to inject into from my `src` pages; an example of which is in https://raw.githubusercontent.com/zslabs/metalsmith-test/master/src/pages/index.md but you'll see in https://github.com/zslabs/metalsmith-test/blob/master/build/index.html it's not compiling to the `<head>` where that block lives; it's just outputting on the page itself. That's the part that's confusing me. Any help would be greatly appreciated. Thanks!

**Comment by ismay** [comment]
So basically what you want to do is replace a block like [this](https://github.com/ismay/ismay.github.io/blob/source/lib/base/base.swig#L8) from a template like [this](https://github.com/ismay/ismay.github.io/blob/source/src/about.swig#L9). That's perfectly possible with just metalsmith-in-place, it's what I'm doing [here](https://github.com/ismay/ismay.github.io). You have a pretty complicated setup btw. Personally I would advise you to use just metalsmith and swig (instead of nunjucks), that way you'll make thing a lot easier for yourself.

Or just start from there, get it working, and then build up. Because right now the amount of buildsteps will make troubleshooting a lot more complicated.

**Comment by zslabs** [comment]
Hey @ismay,
Thanks so much for pointing out your repo, that makes sense. So the thing I was trying to avoid was having to specify an extension of a base layout for things that have a common path; for example articles located in `articles/*.md` should always extend a base layout of `post.html`. That's why I brought in `metalsmith-layouts`, but I wonder if that's what's tripping me up here. Is there anyway to do what I'm looking for automatically by path and also have the ability to extend blocks when needed?

**Comment by ismay** [comment]
> Is there anyway to do what I'm looking for automatically by path and also have the ability to extend blocks when needed?

You might want to take a look at [metalsmith boilerplates](https://github.com/superwolff/metalsmith-boilerplates/tree/layouts/extends).

The main things to keep in mind are: metalsmith-layouts only processes templating syntax in the files in `layouts` and metalsmith-in-place only processes it for files in `src`. So the blocks in [here](https://github.com/zslabs/metalsmith-test/blob/master/src/pages/index.md) won't work if you're only using metalsmith-layouts, it won't process it.

Now there is a PR on metalsmith-layouts that allows you to pass `layout: false` in the front-matter. So once that's merged you'd be able to set a default template for a path, and override it by setting `layout: false`. Then you'd be able to specify a template that can be processed by metalsmith-in-place. But in my opinion that makes your build process too complicated.

**Comment by zslabs** [comment]
Great, thanks for your help with this!

**Comment by ismay** [comment]
No problem, hope it helps! 👍

**Comment by zslabs** [comment]
Ah - so https://github.com/mozilla/nunjucks/issues/460 seems to be what I'm after; which doesn't appear to be how Nunjucks works; and how I'd believe Swig to as well after testing out the boilerplates you mentioned. It seems like plugging into blocks from included partials is not possible.

**Comment by ismay** [comment]
Ah yeah, that makes sense. When included from a partial the engine probably doesn't know which layout your block refers to, because the context differs.

**Comment by dkebler** [comment]
@zslabs  I (and others) have faced the same issue.  Seems it doesn't matter which engine you can't access blocks in a child extension of a parent file that were defined in a file that was included in that parent.

my work around was to merge/assemble the included files in the parent first using another tool then proceed to process your template with nunjucks, handlebars, jade, swig what have you.   

See this http://stackoverflow.com/questions/35496514/nunjucks-blocks-defined-within-include-partial-file-ignored-by-extend

**Comment by zslabs** [comment]
Ah very interesting, thanks for the heads up @dkebler
