### ISSUE TITLE
renaming files

### ISSUE THREAD

**Issue by rstacruz** [superwolff/metalsmith-in-place#4]
When doing this:

```js
    .use(require('metalsmith-in-place')({
      engine: 'jade',
      pattern: '*.jade'
    }))
```

`index.jade` does not get converted into `index.html`. Perhaps it should be made configurable for this to happen.

**Comment by ismay** [comment]
That's correct, files aren't renamed. I've been holding this off, but I agree that it doesn't make sense to not rename files after rendering them.

**Comment by rstacruz** [comment]
want a PR? how do you want the api to look like?

**Comment by ismay** [comment]
Yeah that would be awesome. I'd say an optional `extension` option, which takes a string (the extension without the dot, so `html` for example) and applies it to all files processed by the plugin. Thanks for helping!

**Comment by ismay** [comment]
FYI, I Updated the tests.

**Comment by ismay** [comment]
I think this should be handled by [metalsmith-rename](https://github.com/MoOx/metalsmith-rename). It seems unnecessary to duplicate its functionality. Closing, but let me know if this plugin doesn't solve it for you.
