### ISSUE TITLE
ECT partials

### ISSUE THREAD

**Issue by Dexbonus** [superwolff/metalsmith-in-place#41]
No matter what I try to do I can't seem to get this resolved so any help would be appreciated!

After trying pretty much everything I could think of to get partials working using ECT I decided to replicate the test fixture for partials provided on this repo. I kept the metalsmith js file as simple as possible, only including a use call to metalsmith-in-place (with the engine and partials properties set) and then building.

At first I tried passing a simple object to the partials property and then including that via ```<% include "footer" %>``` (without the file extension) but that resulted in the error:
 **'[Error: Failed to load template footer in page on line 2]'**
and the error:
**'[TypeError: Cannot read property 'ect' of undefined in page on line 2]'** with the file extension

Next I went with the folder option and simply passed the name of it to the partials property while doing the exact same thing in my template file but alas, the same error reared its ugly head.

The only thing that I have found that **DOES** work is directly outputting the content of the partials object (eg. ```<%- @partials.footer %>```) but this approach destroys the way I would normally do my templating.

Any help or insight would be greatly appreciated!

**Comment by ismay** [comment]
Sorry for the late reply. metalsmith-in-place uses consolidate.js for the partials. Unfortunately consolidate.js doesn't support the use of the partials options for ect (see [source code](https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L885)).

You could open an issue or PR there, or use an ect native way.
