### ISSUE TITLE
replace handlebars tags in scss files

### ISSUE THREAD

**Issue by maticrivo** [superwolff/metalsmith-in-place#49]
Hey, is it possible to use metalsmith-in-place to replace handlebars expressions in css/scss files?

**Comment by doodzik** [comment]
Have a look at [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables/blob/master/README.md) option `variables`

**Comment by ismay** [comment]
@doodzik 's recommendation is the most user-friendly solution. However, should you really want to you _can_ use in-place to replace handlebars syntax in any type of file.
