### ISSUE TITLE
npm version isn't latest code

### ISSUE THREAD

**Issue by alexturpin** [superwolff/metalsmith-in-place#53]
Installing the latest version from `npm` doesn't give the latest code, even though the version number will be marked as latest.

To reproduce, go to an empty directory and then:

1) Run `npm install metalsmith-in-place`
2) Go check `index.js` for any mentions of `exposeConsolidate`

**Comment by alexturpin** [comment]
Ah disregard this, there hasn't been a release with the latest code yet. Still not fully awake!

**Comment by ismay** [comment]
👍 You're right, it hasn't been published. Reason for that is that we're working on moving the codebase to a different templating engine, which wouldn't allow for the expose-consolidate option (but should make things a lot better functionality wise 🎆 ).

**Comment by alexturpin** [comment]
No worries at all, looking forward to the new implementation!
