### ISSUE TITLE
Abstract rendering to separate library

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#58]
Abstract rendering to a replaceable render function (so you can use consolidate, jstransformers or whatever). Makes testing simpler and abstracts the rendering to a separate wrapper library (which can then also be used by `metalsmith-layouts` as well).
- Users should also be able to override it.
- Abstract the api so it can fit other rendering libs besides jstransformers.

Would probably be good to release jstransformers and consolidate-compatible wrappers first. Also, after this release scanning for partials, helpers, etc. as separate libs.

**Comment by doodzik** [comment]
I think we need to refactor our code to see what our requirements are.
Or do you have an idea?

**Comment by ismay** [comment]
Well let's see what the parameters for the renderFile function are: `renderFile(files, filename, metadata, source, options)`. That can be shortened to: `renderFile(files, filename, metalsmith, options)`.

Which is almost the same signature as a metalsmith plugin. We can basically use that pattern (delayed execution, or a thunk). So:

```javascript
// this is a render-module
var renderWithJstransfomer = function(options) {
  return function(files, filename, metalsmith) {
    console.log(`rendering ${filename}`);
    // return rendered result, or update files object
  };
};

module.exports = renderWithJstransformer;
```

We can call that render module in `in-place` with:

```javascript
// .. rest of in-place logic
// get renderer
var renderer = renderWithJstransformer(options)
// render file
renderer(files, filename, metalsmith);
// .. rest of in-place logic
```

Now in the code above we can of course replace `renderWithJstransformer` with a renderer from in-place options, or our own default renderer, which would make it a replaceable renderer. Maybe we could even simplify it even further.

But anyway, this wouldn't require too much refactoring. It *is* something that will make this plugin more of a container, instead of a single purpose module, I'm still on the fence about that as well. But the possibilities are nice, and I think that this would work for what we're trying to do.

**Comment by ismay** [comment]
So in a more general way that could look like:

```
// .. rest of in-place logic
// get renderer
var renderer = opts.renderer(options) || defaultRenderer(options)
// render file
renderer(files, filename, metalsmith);
// .. rest of in-place logic
```

**Comment by doodzik** [comment]
Then why not make the render function a metalsmith plugin as well?
The only thing that is missing is the done callback.
Quite cool actually. I didn't notice this.

**Comment by ismay** [comment]
> Then why not make the render function a metalsmith plugin as well?

Yeah I was thinking about that too. But if we're going to make it a metalsmith plugin then why do you need in-place?

Which is why I said:

> It is something that will make this plugin more of a container, instead of a single purpose module, I'm still on the fence about that as well.

Because you don't want to reinvent metalsmith and it's plugin system, and implement it in metalsmith a level deeper.

**Comment by ismay** [comment]
Then again, it is nice to be able to override the templating engine so easily.

**Comment by doodzik** [comment]
> why do you need in-place?

It is an abstraction on top of it. So the code is easier to understand.

> Because you don't want to reinvent metalsmith and it's plugin system, and implement it in metalsmith a level deeper.

I think if we develop in the metalsmith realm we can adopt its patterns even in the library itself. Then we would be consistent.
If it doesn't work well we can always change back.

**Comment by ismay** [comment]
Also, the signature isn't completely similar. A metalsmith plugin accepts `(files, metalsmith, callback)`, instead of `(files, metalsmith, filename)`. But of course our implementation could be refactored to accept similar arguments as a plugin.

> If it doesn't work well we can always change back.

Ok yeah, let's just try it and see how it works.

**Comment by ismay** [comment]
@doodzik I'm gonna try and make some time for this in the upcoming week. Have been busy with moving, but should have some time for it now. Would be nice to get this move to v2 done.

**Comment by doodzik** [comment]
@ismay no problem. 
Unfortunatly I won't have time for development until I'm done with my thesis in february :(

**Comment by ismay** [comment]
No problem, I've been busy as well. Take your time and I'll keep you posted 👍
