### ISSUE TITLE
Check performance

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#61]
- How does it compare to the old 1.x.x version
- How can it be improved further

**Comment by doodzik** [comment]
I'm not sure if we can enhance the speed by that much. So it begs the question if the pursuit is worth our time.

**Comment by ismay** [comment]
Main thing for me is that right now it's all synchronous. Since it involves disk io I think it would be good to make at least those parts async. Would probably be something to tackle at the same time as abstracting the render function, since that's the part that touches the filesystem.

**Comment by doodzik** [comment]
If we make the render function return a promise we can leave that part to our render library.

```
let promises = files.map(file => render(file, options))
Q.all(promises)
.then(done)
```

I don't think we need to invest into benchmark tests in 'this' library.
