### ISSUE TITLE
Name is confusing

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#64]
The names layouts and in-place are a bit confusing (to newcomers especially). Make it more obvious that in-place is the main lib, and that layouts is just a polyfill for languages without extends

**Comment by doodzik** [comment]
I think the first thing we should do is update both readmes to make it more clear.
So I would put this issue on halt for the time being.

**Comment by ismay** [comment]
Ok sounds good! Added to #60.
