### ISSUE TITLE
Should we expect everything to be in src?

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#65]
Metalsmith loads everything from `src`, so it would make sense to design this lib around that assumption. It seems to be what most newcomers expect as well.

On the other hand, the files in src could also be seen as the files that you want in `build`. Whereas wrapper templates are more secondary files, that you don't want to see in your build output for example. Which approach are we taking?

**Comment by doodzik** [comment]
I would say we should conform with metalsmiths' approach as we are developing for that platform.
I don't see the gain in having a separate folder outside of src.

**Comment by ismay** [comment]
> I would say we should conform with metalsmiths' approach as we are developing for that platform.

Definitely.

> I don't see the gain in having a separate folder outside of src.

Well, one thing that makes me consider this is that putting everything in `src` will mean that people will have to manually exclude their base templates, partials, etc. Which I think is cumbersome. Putting stuff outside of `src` would make that easier.

But then again, both approaches don't have to be mutually exclusive. For example, the way that the in-place beta works supports both patterns (see [the way I'm using it](https://gitlab.com/ismay/ismaywolff.nl/tree/master) for example). So yeah, I think you're right: let's just assume that people are putting everything in `src` and design for that (and if we can support other patterns as well that would be nice).

**Comment by ismay** [comment]
Ok, we're assuming that people are going to have their stuff in `src`. Added a todo to #60

**Comment by bmcminn** [comment]
Just to clarify, this is just the default behavior that can be overwritten? because I'm using `source: ./content` for my Metalsmith instance, so will this inherit from the base metalsmith configuration?

**Comment by doodzik** [comment]
it should inherit the base metalsmith configuration.
