### ISSUE TITLE
Run eslint through travis

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#67]
Currently disabled because of incompatibility with earlier versions of node. Use something like https://www.npmjs.com/package/check-node-version to bypass this.

**Comment by doodzik** [comment]
where are we calling eslint in the build process?

**Comment by ismay** [comment]
Oh wait sorry, I misread that :)

**Comment by ismay** [comment]
To answer your question, currently, nowhere. Ideally, before the mocha tests.

**Comment by ismay** [comment]
https://github.com/travis-ci/travis-ci/issues/2877

**Comment by ismay** [comment]
Could run this as a prepublish script

**Comment by ismay** [comment]
https://github.com/segmentio/metalsmith/issues/231
