### ISSUE TITLE
How to specify the template engine?

### ISSUE THREAD

**Issue by jvolker** [superwolff/metalsmith-in-place#68]
I would like to use Nunjucks as template engine with `metalsmith-in-place` using the [jstransformer-nunjucks](https://github.com/jstransformers/jstransformer-nunjucks) module.

How can I configure my build pipeline to use this module? In the latest (2.0 beta) documentation I can't find any details on specifying an engine.

Thanks a lot in advance!

**Comment by ismay** [comment]
Basically you can follow the example from the readme, but substitute nunjucks. You don't have to specify an engine, jstransformer will see that the transformer is installed and apply the transformation to every file with the appropriate extension.

**Comment by jvolker** [comment]
Thanks. I now managed to get Nunjucks working. I think it’s worth mentioning the https://github.com/jstransformers/inputformat-to-jstransformer/blob/master/dictionary.json list in the Readme. It would help understanding how `metalsmith-in-place` sees the installed transformers and making sure the files to be processed actually have the right extension.

**Comment by ismay** [comment]
Good idea. However that is specific to jstransformers and we're phasing out the coupling of in-place to a specific templating engine. However, it would be a good idea to put this in the docs for our jstransformer wrapper. Thanks!

**Comment by samuelgoldenbaum** [comment]
Struggling to get nunjucks working with in-place. Please can someone provide some steps

**Comment by ismay** [comment]
1. Install metalsmith-in-place, metalsmith etc. (follow the readme)
2. Install https://github.com/jstransformers/jstransformer-nunjucks
3. Give the files that you want to transform a .njk extension

See also https://github.com/superwolff/metalsmith-engine-jstransformer

**Comment by samuelgoldenbaum** [comment]
Was missing the extension! Thanks

**Comment by ismay** [comment]
Cool, glad it helped! 👍 We're working on updating the documentation so this'll be more clear.

**Comment by samuelgoldenbaum** [comment]
Seeing issues with `extends` so layouts are not able to read from any path outside the same root as the templates. Is this a known issue?

`{% extends "../layouts/layout.njk" %}`

**Comment by ismay** [comment]
Yup: https://github.com/jstransformers/jstransformer-nunjucks/issues/10
