### ISSUE TITLE
How do I pass the files object to a helper?

### ISSUE THREAD

**Issue by gotofritz** [superwolff/metalsmith-in-place#75]
Using handlebars. I have  a template with a call to a helper

    {{postlist}}

I have a simple helper there. What I want to do is to create a list of posts which match a certain criteria (the details are unimportant)

```
helpers.postlist = (param, options) => {
  return "-----POSTLIST-----";
}
```

But no reference to the current `files` or `metalsmith` object is passed on to the helper. How do I go about passing that file list into the helper? It sounds silly having to re-read the directory from within the helper, as I have already all the information I need in the files object.

Thanks.

**Comment by ismay** [comment]
That's not possible with the current version (1.x.x). We're working on a new release (2.x.x) where you'll be able to use custom engines (https://github.com/superwolff/metalsmith-in-place/pull/72, https://github.com/superwolff/metalsmith-engine-jstransformer) which would allow you to modify the rendering logic. You could then modify the engine to pass the files object as locals.

Check out the pr. It's ready for use and should be relatively self-explanatory. All you'd need to do is modify the engine a little.
