### ISSUE TITLE
Create consolidate engine

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-in-place#77]

**Comment by nephiw** [comment]
I agree - most of the internet says that passing a string for the engine would make it work. But it looks like that was a feature of version 1 that was removed in 2.

**Comment by ismay** [comment]
That's right. We've switched to jstransformers for version 2 as the default engine. But engines can be switched out now so it's relatively straightforward to create a consolidate engine.

Or you can use version 1, which uses consolidate by default and works like you said.

**Comment by bashaus** [comment]
In the example in the document, I notice that it refers to Consolidate via metalsmith-engine-consolidate. I cannot find this reference in npmjs.com.

Can we update the README?

```
var metalsmith = require('metalsmith')
var inPlace = require('metalsmith-in-place')
var Consolidate = require('metalsmith-engine-consolidate')

metalsmith(__dirname)
  .use(inPlace({
    engine: Consolidate
  }))
  .build(function(err){
    if (err) throw err;
  });
```

**Comment by ismay** [comment]
> I cannot find this reference in npmjs.com

That's correct, the package doesn't exist. I can see how that can be confusing (it's just meant to illustrate the syntax). We can replace the example with `metalsmith-engine-jstransformer`, which is the default engine. So to this:

```
var metalsmith = require('metalsmith')
var inPlace = require('metalsmith-in-place')
var Jstransformer = require('metalsmith-engine-jstransformer')

metalsmith(__dirname)
  .use(inPlace({
    engine: Jstransformer
  }))
  .build(function(err){
    if (err) throw err;
  });
```

It would then be good to add a note that this isn't necessary as it's already the default. @bashaus Would you care to submit a PR for that?

**Comment by bashaus** [comment]
Hey @ismay 

Thanks for responding so promptly.

This doesn't really solve the problem that I am experiencing and the example that the documentation is trying to convey. 

How do you set an engine other than jstransformer? I'm unclear on how to use Consolidate. It would be good for legacy developers to have this in the documentation.

**Comment by ismay** [comment]
> How do you set an engine other than jstransformer?

Exactly like in the documentation. This library allows other engines to be passed in. However, there currently is only one engine available (jstransformer). So if you want to use consolidate someone needs to create the wrapper (engine) first (which is not too difficult). See https://github.com/superwolff/metalsmith-engine-jstransformer for an example.

All the documentation does is show that a custom engine can be used. We extracted all the engine specific logic from in-place because we were running into too much situations where bug fixes and specific use-cases were clogging up the main library. This approach creates a clean separation between the plugin and the rendering logic and even allows you to modify the rendering logic easily. Hope that clears it up.

**Comment by ismay** [comment]
Not necessary, https://github.com/jstransformers/jstransformer-consolidate can already be used.
