### ISSUE TITLE
Won't render handlebars

### ISSUE THREAD

**Issue by Jackbennett** [superwolff/metalsmith-in-place#81]
I've looked at every example I can find and the source but I can't see why this just isn't getting rendered at all. I tried `inPlace({pattern: '**/'.html'})` too, I can't specify the handlebars engine because it doesn't expose a render method so jstransform is supposed to deal with it isn't it?

build.js
```javascript
var Metalsmith = require('metalsmith');
var layouts = require('metalsmith-layouts');
var inPlace = require('metalsmith-in-place');
var autoprefixer = require('metalsmith-autoprefixer');
var assets = require('metalsmith-assets');
var markdown = require('metalsmith-markdown');
var permalinks = require('metalsmith-permalinks');
var collections = require('metalsmith-collections');
var debug = require('metalsmith-debug');

Metalsmith(__dirname)
  .destination('./public')
  .source('./content')
  .clean(true)
  .use(assets({
    source: './assets',
    destination: './assets'
  }))
  .use(inPlace())
  .use(collections({
      blog:{
        pattern:'blog/**/*.html'
      }
  }))
  .use(permalinks({
    pattern: ':title',
    relative: false,
    linksets: [{
        match: { collection: 'blog' },
        pattern: ':collection/:title'
    }]
  }))
  .use(autoprefixer())
  .use(layouts({
    engine: 'handlebars',
    directory: './template',
    default: 'default.hbs',
    partials: './template/partial',
    pattern: '**/*.html'
  }))
  .use(debug())  // set $env:DEBUG='metalsmith:*' to see output
  .build(function(err) {
    if (err) throw err;
  })
```

content/blog/index.html
```html
<h1>List of blog pages.</h1>

{{#each post in blog}}
    <h1>{{post.title}}</h1>
{{/each}}
```

public/blog/index.html
```html
...template
    </section>

    <div class="main">
        <h1>List of blog pages.</h1>

{{#each post in blog}}
    <h1>{{post.title}}</h1>
{{/each}}

    </div>

    <footer>
...template
```

**Comment by jvolker** [comment]
I had similar problems understanding this in the beginning. 
As very shortly described [here](https://github.com/superwolff/metalsmith-in-place#installation) …
> For example, to render handlebars templates, you'd need to install `metalsmith-in-place` and `jstransformer-handlebars`.

So just install `[jstransformer-handlebars](https://github.com/jstransformers/jstransformer-handlebars)` in addition to `metalsmith-in-place`. Jstransformer detects the `jstransformer-handlebars` plugin-in automatically. 
But you also have to make sure your files have the right extension for the plugin you want to use. According to [this list](https://github.com/jstransformers/inputformat-to-jstransformer/blob/master/dictionary.json) jstransformer allows `*.handlebars` and `*. hbs` to be passed to the Handlebars transformer.

**Comment by Jackbennett** [comment]
Oh I was so close with that I installed `var handlebars = require('jstransformer')(require('jstransformer-handlebars'))` and gave inPlace then `engine: handlebars.Compile` but of course still stuck. I didn't realise it ignored the pattern.

**Comment by Jackbennett** [comment]
Somehow without using `inPlace({pattern: '**/*.hbs'})` pattern it's mangingling my font .woff etc files and the browser can't render them.

**Comment by jvolker** [comment]
Yes, you basically use the pattern to limit the files in-place is going to touch.

**Comment by ismay** [comment]
> Yes, you basically use the pattern to limit the files in-place is going to touch.

Exactly. Thanks for the help @jvolker !

**Comment by Jackbennett** [comment]
Thanks for the help

>use the pattern to limit the files in-place is going to touch

That makes sense but having to install jstransform-handlebars, which ignores any pattern given to it and wants files named .hbs or .handlebars anyway. If a config is `{engine: 'handlebars', pattern: '**/*.potatoes`}` then it's pretty clear to run handlebars against anything that has a file extension potatoes no?

Or if you do nothing and the default pattern `**` it's processing my font files which breaks them? Pretty weird behaviour. It's not like I installed jstransform-woff.

Wouldn't it be even clearer with something akin to
```javascript
var inPlace = require('metalsmith-in-place')
var Renderer= require('jstransformer-handlebars')
inPlace({
  engine: Renderer,
  pattern: 'specific/**/*.create'
})
```

**Comment by ismay** [comment]
> If a config is {engine: 'handlebars', pattern: '**/*.potatoes}` then it's pretty clear to run handlebars against anything that has a file extension potatoes no?

It is, but this plugin is agnostic to the engine used. So while this makes sense for jstransformer, it doesn't necessarily make sense for other engines.

> Or if you do nothing and the default pattern ** it's processing my font files which breaks them? Pretty weird behaviour. It's not like I installed jstransform-woff.

It doesn't know which files you want to process. The default pattern is `**`, so it's expected behaviour.
