### ISSUE TITLE
Cannot get jstransformer to work

### ISSUE THREAD

**Issue by Zearin** [superwolff/metalsmith-in-place#86]
Okay, so I really want to unlock the jstransformer power of this plugin.  But I cannot get it to work!

----

First of all, the README claims that passing `engine` to the plugin is optional.  When I leave it blank, I get a fatal error that says the `engine` option is required.  Very frustrating.

Next, I tried to explicitly set `engine` to JSTransformer.  Sounds simple enough, right?  Unfortunately, I found it surprisingly confusing.  Here’s why.

----

The README says the default engine is “jstransformer”, but that word links to **`metalsmith-engine-jstransformer`** instead.  I looked in the source code, and that appears to be what is used by `metalsmith-in-place`.  

So, the README _text_ says one thing, the README _links_ to a different thing, and finally there is a third project [`metalsmith-jstransformer`](RobLoach/metalsmith-jstransformer).

After trying both `jstransformer` and `metalsmith-engine-jstransformer`, I kept getting the same error:

```
Error: Unknown template engine: "function Engine(files, metalsmith, options) {
    _classCallCheck(this, Engine);

    this.files = files;
    this.options = options;
    this.metadata = metalsmith.metadata();
    this.source = metalsmith.source();
  }"
```

Thoroughly frustrated and baffled, I tried using `metalsmith-jstransformer` instead.  That failed, too.  (Yes, I also installed the necessary `jstransformer-*` plugins.  For now, I was just using Handlebars.)

As a matter of fact, I remained confused about the relationship between `metalsmith-jstransformer` and this project until I began writing this issue.  In the process of writing, I now understand that `metalsmith-jstransformer` appears merely to have been an inspiration, and is not required or even used by this project.  

**This relationship needs to be clearly stated on the README,**  along with a clear statement about the `metalsmith-engine-jstransformer`, and whether `metalsmith-engine-*` is a sub-naming scheme to be used by all engines for this plugin.

I’m dying to try out this use of `metalsmith-in-place` out…but please tell me what is going on!  I’m pretty frustrated after trying to figure this out for a couple of hours.  

Please help!  And May the Source Be With You™.

**Comment by ismay** [comment]
Could you provide a link to a repository demonstrating the problem, that way I can take a look at your setup.

**Comment by Zearin** [comment]
@ismay NOW I know what was going wrong.  I was using an outdated version. `/facepalm`

Sorry for freaking out.  I must remember never to open issues at the end of the day when my brain is too tired to check the obvious. 

Thank you for the quick response!

**Comment by ismay** [comment]
Ah great. I think in this case part of the problem is also that the readme is still a little bit confusing. I'll see what I can do about that.
